### ISSUE TITLE
When DB is clean Politikon display 'IndexError at /'

### ISSUE THREAD

**Issue by JulianVolodia** [KlubJagiellonski/Politikon#224]
> IndexError at /
>
> list index out of range

Fix ./politikon/views.py:29 
```
front_event = home_events[0]
```
checking if not null.

**Comment by ppeczek** [comment]
Thanks! Do you want to take care for this issue? :)

**Comment by JulianVolodia** [comment]
Today I will (greetings from tech soup :P )

Also some fixes in ReadMe waiting in my TODO list.

**Comment by ppeczek** [comment]
Perfect! @JulianVolodia , @WojtekReu please consider moving parts of README to wiki. It is much more readable and easy for new developers when written in wiki

**Comment by JulianVolodia** [comment]
I vote to leave normal (abbrev.) ReadMe (for developers) cause of KISS (mayby even repeat that Wiki ). Add more desc if there is some known issues, some repetitive errors depend of env and Q&A FAQ (for troubleshooting).

For me, good ReadMe (in easy points which are reproducable) is greatest thing for new person in project.

@ppeczek 
btw. maybe we should discuss on Slack issue tracker "copy-paste" from Trello here. I saw many things were added. But maybe it should be removed from Trello after pasteing it here?
btw2. could you check FB? ;)

**Comment by JulianVolodia** [comment]
I agree that some of people do not like readme but... it's just frog - you must swallow it and forget. Read and know for me.

I think we will be shrinking ReadMe because more and more things will be automated.
BTW. is off-topic.

**Comment by JulianVolodia** [comment]
It cause error when DB have data :P 

Fix is comming in PR (work in both cases)...
