### ISSUE TITLE
fix docker_run.sh and add docker_bye.sh

### ISSUE THREAD

**Issue by JulianVolodia** [KlubJagiellonski/Politikon#246]
I fixed docker_run.sh script for:
- no need to press Return twice to get shell after docker instance up
- posibility of starting multiple shells

I adding docker_stop.sh for conveninence.

**Comment by ppeczek** [comment]
This isn't an issue. Post it as a commit message, please.

**Comment by JulianVolodia** [comment]
I wanted to notice changes (and show that work is done already). To not be repeated by someone (and show change here).

I think more people will look for it here firstly.

**Comment by ppeczek** [comment]
You probably will have to fix conflicts, because I've PR'd today docker_run

**Comment by ppeczek** [comment]
Please next time create PR with message: "not RTM" so we will know you are working on this. This is not an issue.

**Comment by JulianVolodia** [comment]
Could you merge your change? And why we are using latest? it's the latest stable? ;) We should test on postgresql which are on Prod env. Are prod env build from dockerfile?

**Comment by ppeczek** [comment]
merged. we are using latest stable. no, prod is not built from dockerfile

**Comment by ppeczek** [comment]
BTW what is this docker_bye for?

**Comment by JulianVolodia** [comment]
stopping db and vm. Some of devs could appreciate to stop them before shutting up the system.

**Comment by JulianVolodia** [comment]
PR in review.

**Comment by ppeczek** [comment]
It isn't the best idea to close issue manually when PR in review. Check out this article: https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by JulianVolodia** [comment]
ya know ;) sorry ;)

**Comment by JulianVolodia** [comment]
Could somebody test it on OS X? Any programmer work on it?

**Comment by ppeczek** [comment]
Hey, @JulianVolodia, how about forcing execution of docker_bye.sh when leaving docker? Is it possible?

**Comment by JulianVolodia** [comment]
Leaving? Do you mean - exiting shell? I wanted to have more shells (like it works e.g. with vagrant boxes...) open and in next step run local server on container start (so you have working env OOTB).

**Comment by JulianVolodia** [comment]
Feature which gives 'bye' possibility - you could (fast) close containers used with that env (probably it wouldn't be one set of Docker containers on sb's machine...)
