### ISSUE TITLE
Fix the JSON example data

### ISSUE THREAD

**Issue by JulianVolodia** [KlubJagiellonski/Politikon#248]
WIP

Import in container fails.

# TODO issue with data json file
django.core.serializers.base.DeserializationError: Problem installing fixture '/app/db_dumps/local_test_data.json': Event has no field named u'is_front'

**Comment by JulianVolodia** [comment]
Ouch... #225 is the same... sorry.

**Comment by WojtekReu** [comment]
Value is_front is no longer used. I forgot remove it.

**Comment by JulianVolodia** [comment]
this is duplicate issue
