### ISSUE TITLE
Feature - user add event proposal

### ISSUE THREAD

**Issue by JulianVolodia** [KlubJagiellonski/Politikon#290]
Story:
1st iterations.
1) user could add proposal (event with moderate flag - 'not seen' with info about the author (id))
2) moderator give opinion
3) new event will be shown

2nd iterations.
4) view with proposals for user
5) history for moderator

3rd iterations.
6) user asks for re-op his proposal

**Comment by ppeczek** [comment]
Any success so far? :)

**Comment by WojtekReu** [comment]
Not finished yet.
1) Creating new event form: https://github.com/KlubJagiellonski/Politikon/pull/299
2) Saving this form
TODO:
3) Switch in Event model (name may be ``proposal`` or ``status``) cause not displaying on events list.
4) List of user events

**Comment by JulianVolodia** [comment]
Closed by #299
